name: Compiler workflow for kylin
on:
  workflow_dispatch:
    inputs:
      redisv:
        description: 'redis version'
        default: '8.0.2'
        required: false
        type: string
      osv:
        description: 'kylin version'
        default: '10sp3'
        required: false
        type: string
      pgsz-amd64:
        description: 'jemalloc page'
        default: '12'
        required: false
        type: string
      pgsz-arm64:
        description: 'jemalloc page'
        default: '16'
        required: false
        type: string

jobs:
  compile:
    strategy:
      matrix:
        platform: ["amd64", "arm64"]
        # platform: ["amd64"]
    runs-on: ubuntu-latest
    steps:
    - name: Setup jemalloc compile option
      id: jemalloc
      run: |
        if [ ${{ matrix.platform }} = "amd64" ]; then
          echo "PGSZ=${{ inputs.pgsz-amd64 }}" >> $GITHUB_OUTPUT
        else
          echo "PGSZ=${{ inputs.pgsz-arm64 }}" >> $GITHUB_OUTPUT
        fi
    - name: Setup redis main version
      id: redismain
      run: |
        echo "RM=$(echo ${{ inputs.redisv }} | cut -d'.' -f1)" >> $GITHUB_OUTPUT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Prepare redis src
      run: |
        wget https://download.redis.io/releases/redis-${{ inputs.redisv }}.tar.gz
        tar -xzf redis-${{ inputs.redisv }}.tar.gz
        ls -lh redis-${{ inputs.redisv }}
        cp -r redis-${{ inputs.redisv }} redis-src-round1
        cp -r redis-${{ inputs.redisv }} redis-src-round2
      working-directory: /tmp
    - name: compile redis && strip binaries(round 1, without redisearch)
      run: |
        sed -i 's/^SUBDIRS.*$/SUBDIRS = redisjson redistimeseries redisbloom/' /tmp/redis-src-round1/modules/Makefile
        if [ ${{ steps.redismain.outputs.RM }} -lt 8 ]; then
          docker run --platform linux/${{ matrix.platform }} --rm -v /tmp/redis-src-round1:/workspace -w /workspace djangoyi/redis-compiler:kylin-${{ inputs.osv }} bash -c "python3 -m venv /opt/py && source /opt/py/bin/activate && JEMALLOC_CONFIGURE_OPTS='--with-lg-page=${{ steps.jemalloc.outputs.PGSZ }}' make BUILD_TLS=yes USE_SYSTEMD=yes && PREFIX=/workspace/redis-output make install && find /workspace/redis-output -type f -exec strip "{}" \;"
        else
          docker run --platform linux/${{ matrix.platform }} --rm -v /tmp/redis-src-round1:/workspace -w /workspace djangoyi/redis-compiler:kylin-${{ inputs.osv }} bash -c "python3 -m venv /opt/py && source /opt/py/bin/activate && export BUILD_TLS=yes;export BUILD_WITH_MODULES=yes;export INSTALL_RUST_TOOLCHAIN=yes;export DISABLE_WERRORS=yes;JEMALLOC_CONFIGURE_OPTS='--with-lg-page=${{ steps.jemalloc.outputs.PGSZ }}' make -j "$(nproc)" all && PREFIX=/workspace/redis-output make install && find /workspace/redis-output -type f -exec strip "{}" \;"
        fi
    - name: pack bin files
      run: |
        cp -r redis-src-round1/redis-output ./
        tar -czf /tmp/redis-${{ inputs.redisv }}-${{ matrix.platform }}.tgz redis-output/*
      working-directory: /tmp
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kylin-${{ matrix.platform }}
        path: /tmp/redis-${{ inputs.redisv }}-${{ matrix.platform }}.tgz

  release:
    runs-on: ubuntu-latest
    needs: compile
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # - name: Remove release
    #   uses: liudonghua123/delete-release-action@v1
    #   with:
    #     release_name: redis-${{ inputs.redisv }}_ubuntu-${{ inputs.osv }}
    #     suppress_errors: true
    # - name: Remove tag
    #   run: |
    #     git tag -d mongo-${{ needs.export.outputs.mongo }}_ubuntu-${{ needs.export.outputs.ubuntu }} || :
    #     git push origin --delete mongo-${{ needs.export.outputs.mongo }}_ubuntu-${{ needs.export.outputs.ubuntu }} || :
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        pattern: kylin-*
        path: release
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/kylin-*/*
        tag_name: redis-${{ inputs.redisv }}_kylin-${{ inputs.osv }}
